from __future__ import annotations

import html
import re
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
SITE_DIR = ROOT / "site"
TEMPLATE_DIR = SITE_DIR / "_templates"
HEADER_MARKER = "<!-- Generated by tools/build_site.py: do not edit header/footer by hand. -->"

NAV_GROUPS = [
    {
        "key": "ancient-medieval",
        "label": "Ancient &amp; Medieval",
        "pages": [
            ("antiquity.html", "Antiquity"),
            ("late-antiquity.html", "Late Antiquity"),
            ("south-asian.html", "South Asian"),
            ("east-asian.html", "East Asian"),
            ("islamic.html", "Islamic"),
            ("jewish.html", "Jewish"),
            ("scholasticism.html", "Scholasticism"),
        ],
    },
    {
        "key": "early-modern",
        "label": "Early Modern",
        "pages": [
            ("renaissance.html", "Renaissance"),
            ("early-modern.html", "Early Modern"),
        ],
    },
    {
        "key": "modern",
        "label": "Modern",
        "pages": [
            ("nineteenth-century.html", "19th Century"),
            ("phenomenology.html", "Phenomenology"),
            ("analytic.html", "Analytic"),
        ],
    },
    {
        "key": "contemporary",
        "label": "Contemporary",
        "pages": [
            ("consciousness-science.html", "Consciousness Science"),
            ("machine-minds.html", "Machine Minds"),
            ("moral-status.html", "Moral Status"),
        ],
    },
]

DIRECT_LINKS = [
    ("index.html", "Home"),
    ("glossary.html", "Glossary"),
    ("about.html", "About"),
]

HEADER_RE = re.compile(r"<header class=\"site-header\">.*?</header>\s*", re.S)
FOOTER_RE = re.compile(r"<footer class=\"site-footer\">.*?</footer>\s*", re.S)
BODY_OPEN_RE = re.compile(r"<body>\s*", re.S)
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S)
NAV_RE = re.compile(r"<nav class=\"site-nav\">(.*?)</nav>", re.S)
MAIN_RE = re.compile(r"(<main\b[^>]*>)(.*?)(</main>)", re.S)
ACTIVE_SUBLINK_RE = re.compile(r'<a href=\"([^\"]+)\" class=\"nav-sublink active\">')
ACTIVE_TOP_RE = re.compile(r'<a href=\"([^\"]+)\" class=\"nav-link active\">')
GLOSSARY_LINK_RE = re.compile(r'(<a\b[^>]*href=\"glossary\.html#([^\"]+)\"[^>]*)(>)')
CLASS_ATTR_RE = re.compile(r'class=(\"|\')(.*?)\1', re.I)
GLOSSARY_ANCHOR_INNER_RE = re.compile(r'<a\b[^>]*href=\"glossary\.html#[^\"]+\"[^>]*>(.*?)</a>', re.S)
STANDFIRST_P_RE = re.compile(r'(<p\b[^>]*class=\"[^\"]*\bstandfirst\b[^\"]*\"[^>]*>)(.*?)(</p>)', re.S)
ERA_PAGE_HEADER_RE = re.compile(r'(<header\b[^>]*class=\"[^\"]*\bera-page-header\b[^\"]*\"[^>]*>)(.*?)(</header>)', re.S)
CONTEMP_INTRO_RE = re.compile(r'(<section\b[^>]*class=\"[^\"]*\bcontemp-intro\b[^\"]*\"[^>]*>)(.*?)(</section>)', re.S)
GLOSSARY_ENTRY_RE = re.compile(r'<h3 id="([^"]+)">([^<]+)</h3>\s*<p>(.*?)</p>', re.S)
SCRIPT_TAG_RE = re.compile(r'\s*<script\b[^>]*src=\"site\.js\"[^>]*></script>\s*', re.S)
MARKER_RE = re.compile(rf'\s*{re.escape(HEADER_MARKER)}\s*', re.S)
H1_RE = re.compile(r'<h1>(.*?)</h1>', re.S)

AUTO_GLOSSARY_LINKS = [
    ("global-workspace-theory", ("global workspace theory",)),
    ("global-neuronal-workspace", ("global neuronal workspace",)),
    ("phenomenal-consciousness", ("phenomenal consciousness",)),
    ("access-consciousness", ("access consciousness",)),
    ("predictive-processing", ("predictive processing",)),
    ("active-inference", ("active inference",)),
    ("integrated-information-theory", ("integrated information theory",)),
    ("integrated-information", ("integrated information",)),
    ("embodied-cognition", ("embodied cognition",)),
    ("extended-mind", ("extended mind",)),
    ("collective-intentionality", ("collective intentionality",)),
    ("shared-intentionality", ("shared intentionality",)),
    ("joint-attention", ("joint attention",)),
    ("cognitive-architecture", ("cognitive architecture",)),
    ("mental-representation", ("mental representation", "mental representations")),
    ("mental-causation", ("mental causation",)),
    ("representationalism", ("representationalism",)),
    ("social-cognition", ("social cognition",)),
    ("self-consciousness", ("self-consciousness", "self consciousness")),
    ("self-model", ("self-model", "self model")),
    ("theory-of-mind", ("theory of mind",)),
    ("mindreading", ("mindreading",)),
    ("metacognition", ("metacognition",)),
    (
        "higher-order-theory",
        (
            "higher-order theory",
            "higher-order theories",
            "higher-order thought theory",
            "higher-order thought theories",
        ),
    ),
    ("attention-schema", ("attention schema", "attention schema theory")),
    ("biological-naturalism", ("biological naturalism",)),
    ("cartesian-theater", ("cartesian theater",)),
    ("multiple-drafts-model", ("multiple drafts model",)),
    ("recurrent-processing-theory", ("recurrent processing theory", "recurrent processing")),
    ("anomalous-monism", ("anomalous monism",)),
    ("neutral-monism", ("neutral monism",)),
    ("semantic-externalism", ("semantic externalism",)),
    ("supervenience", ("supervenience",)),
    ("nonreductive-physicalism", ("nonreductive physicalism",)),
    ("intentionality", ("intentionality",)),
    ("volition", ("volition",)),
    ("working-memory", ("working memory",)),
]


@dataclass(frozen=True)
class PageContext:
    filename: str
    title: str
    active_top_link: str | None
    active_group: str | None
    active_page: str | None


def load_template(name: str) -> str:
    return (TEMPLATE_DIR / name).read_text(encoding="utf-8").strip()


def infer_page_context(source: str, filename: str) -> PageContext:
    title_match = TITLE_RE.search(source)
    title = title_match.group(1).strip() if title_match else f"{filename} · Digital Minds"

    active_top = None
    active_group = None
    active_page = None

    nav_match = NAV_RE.search(source)
    if nav_match:
        nav = nav_match.group(1)
        top_match = ACTIVE_TOP_RE.search(nav)
        if top_match:
            href = top_match.group(1)
            if href in {"index.html", "glossary.html", "about.html"}:
                active_top = href
        sub_match = ACTIVE_SUBLINK_RE.search(nav)
        if sub_match:
            active_page = sub_match.group(1)
            active_group = group_key_for_page(active_page)

    if filename == "index.html":
        active_top = "index.html"
    elif filename == "glossary.html":
        active_top = "glossary.html"
    elif filename == "about.html":
        active_top = "about.html"

    inferred_group = group_key_for_page(filename)
    if inferred_group:
        active_group = inferred_group
        active_page = filename

    return PageContext(
        filename=filename,
        title=title,
        active_top_link=active_top,
        active_group=active_group,
        active_page=active_page,
    )


def group_key_for_page(filename: str | None) -> str | None:
    if not filename:
        return None
    for group in NAV_GROUPS:
        if any(page_filename == filename for page_filename, _ in group["pages"]):
            return group["key"]
    return None


def render_header(context: PageContext) -> str:
    parts = [HEADER_MARKER, '<header class="site-header">', '  <div class="site-header-inner">']
    parts.append('    <a href="index.html" class="site-title"><em>A History of Mind</em></a>')
    parts.append('    <nav class="site-nav" aria-label="Primary">')
    parts.append(render_direct_link("index.html", "Home", context.active_top_link == "index.html"))

    for group in NAV_GROUPS:
        parts.append(render_group(group, context))

    parts.append(render_direct_link("glossary.html", "Glossary", context.active_top_link == "glossary.html"))
    parts.append(render_direct_link("about.html", "About", context.active_top_link == "about.html"))
    parts.append('    </nav>')
    parts.append('  </div>')
    parts.append('</header>')
    return "\n".join(parts)


def render_direct_link(href: str, label: str, is_active: bool) -> str:
    active_class = " active" if is_active else ""
    return f'      <a href="{href}" class="nav-link{active_class}">{label}</a>'


def render_group(group: dict, context: PageContext) -> str:
    is_active = context.active_group == group["key"]
    submenu_id = f'submenu-{group["key"]}'
    group_class = 'nav-group active' if is_active else 'nav-group'
    button_class = 'nav-link nav-label active' if is_active else 'nav-link nav-label'
    button = (
        f'        <button type="button" class="{button_class}" '
        f'aria-haspopup="true" aria-expanded="false" aria-controls="{submenu_id}">'
        f'{group["label"]}<span class="nav-caret" aria-hidden="true"> &#9662;</span></button>'
    )
    submenu = [
        f'        <div class="nav-submenu" id="{submenu_id}">'
    ]
    for href, label in group["pages"]:
        active_class = ' active' if context.active_page == href else ''
        submenu.append(f'          <a href="{href}" class="nav-sublink{active_class}">{label}</a>')
    submenu.append('        </div>')
    return "\n".join([f'      <div class="{group_class}">', button, *submenu, '      </div>'])


def build_page(source: str, context: PageContext) -> str:
    header = render_header(context)
    footer = load_template("footer.html")
    head_extra = load_template("head-extra.html")

    page = SCRIPT_TAG_RE.sub("\n", source)
    page = MARKER_RE.sub("\n", page)
    page = FOOTER_RE.sub("", page)
    page = HEADER_RE.sub(header + "\n", page)
    page = inject_head_extra(page, head_extra)
    page = normalize_title_entities(page)
    page = autolink_glossary_terms(page, context)
    page = autolink_entry_pages(page, context)
    if footer not in page:
        page = page.replace("</body>", footer + "\n</body>")
    page = ensure_glossary_attrs(page)
    page = strip_subtitle_glossary_links(page)
    return page


def inject_head_extra(page: str, head_extra: str) -> str:
    if head_extra in page:
        return page
    return page.replace("</head>", f"  {head_extra}\n</head>")


def normalize_title_entities(page: str) -> str:
    def repl(match: re.Match[str]) -> str:
        normalized = match.group(1)
        while True:
            unescaped = html.unescape(normalized)
            if unescaped == normalized:
                break
            normalized = unescaped
        normalized = html.escape(normalized, quote=False)
        return f'<title>{normalized}</title>'

    return TITLE_RE.sub(repl, page, count=1)


def ensure_glossary_attrs(page: str) -> str:
    entries = glossary_entries()

    def ensure_class_token(tag_open: str, token: str) -> str:
        class_match = CLASS_ATTR_RE.search(tag_open)
        if not class_match:
            return f'{tag_open} class="{token}"'

        class_value = class_match.group(2)
        class_tokens = class_value.split()
        if token in class_tokens:
            return tag_open

        updated = " ".join((*class_tokens, token)).strip()
        return f'{tag_open[:class_match.start(2)]}{updated}{tag_open[class_match.end(2):]}'

    def ensure_attr(tag_open: str, attr: str, value: str) -> str:
        if re.search(rf'\b{re.escape(attr)}\s*=', tag_open):
            return tag_open
        escaped = html.escape(value, quote=True)
        return f'{tag_open} {attr}="{escaped}"'

    def repl(match: re.Match[str]) -> str:
        tag_open, term_id, tag_close = match.group(1), match.group(2), match.group(3)
        updated = ensure_class_token(tag_open, "gloss-term")
        definition = entries.get(term_id, {}).get("definition")
        if definition:
            updated = ensure_attr(updated, "data-def", definition)
        updated = ensure_attr(updated, "data-glossary-enhanced", "true")
        return f"{updated}{tag_close}"

    return GLOSSARY_LINK_RE.sub(repl, page)


def strip_subtitle_glossary_links(page: str) -> str:
    def strip_glossary_anchors(fragment: str) -> str:
        return GLOSSARY_ANCHOR_INNER_RE.sub(lambda match: match.group(1), fragment)

    def replace_inner(pattern: re.Pattern[str], html_fragment: str) -> str:
        def repl(match: re.Match[str]) -> str:
            return f"{match.group(1)}{strip_glossary_anchors(match.group(2))}{match.group(3)}"

        return pattern.sub(repl, html_fragment)

    page = replace_inner(STANDFIRST_P_RE, page)
    page = replace_inner(ERA_PAGE_HEADER_RE, page)
    page = replace_inner(CONTEMP_INTRO_RE, page)
    return page


@lru_cache(maxsize=1)
def glossary_entries() -> dict[str, dict[str, str]]:
    glossary_path = SITE_DIR / "glossary.html"
    if not glossary_path.exists():
        return {}

    entries: dict[str, dict[str, str]] = {}
    source = glossary_path.read_text(encoding="utf-8")
    for term_id, heading, definition_html in GLOSSARY_ENTRY_RE.findall(source):
        definition = re.sub(r"<[^>]+>", " ", definition_html)
        definition = html.unescape(re.sub(r"\s+", " ", definition)).strip()
        entries[term_id] = {
            "heading": heading.strip(),
            "definition": definition,
        }
    return entries


def autolink_glossary_terms(page: str, context: PageContext) -> str:
    if context.filename == "glossary.html":
        return page

    main_match = MAIN_RE.search(page)
    if not main_match:
        return page

    main_content = main_match.group(2)
    existing_links = set(re.findall(r'href="glossary\.html#([^"]+)"', main_content))
    entries = glossary_entries()

    for term_id, variants in AUTO_GLOSSARY_LINKS:
        if term_id in existing_links or term_id not in entries:
            continue
        main_content, linked = autolink_term_once(main_content, term_id, variants, entries[term_id]["definition"])
        if linked:
            existing_links.add(term_id)

    return "".join(
        (
            page[: main_match.start()],
            main_match.group(1),
            main_content,
            main_match.group(3),
            page[main_match.end() :],
        )
    )


@lru_cache(maxsize=1)
def entry_page_aliases() -> dict[str, tuple[str, ...]]:
    aliases_by_href: dict[str, set[str]] = {}
    ambiguous_single_word_aliases = {
        "brown",
        "james",
        "lewis",
        "long",
        "list",
        "hamilton",
        "great",
    }

    for path in sorted(SITE_DIR.glob("*.html")):
        if path.name in {"index.html", "about.html", "glossary.html"}:
            continue
        source = path.read_text(encoding="utf-8")
        if '<section class="essay-header">' not in source:
            continue

        match = H1_RE.search(source)
        if not match:
            continue

        title = html.unescape(re.sub(r"<[^>]+>", " ", match.group(1)))
        title = re.sub(r"\s+", " ", title).strip()
        title_tokens = [token.strip(".,;:!?()[]{}“”‘’\"'") for token in title.split() if token.strip(".,;:!?()[]{}“”‘’\"'")]

        aliases: set[str] = set()
        if title:
            aliases.add(title)
            aliases.add(f"{title}’s")
            aliases.add(f"{title}'s")

        if len(title_tokens) >= 2:
            surname = title_tokens[-1]
            if surname and len(surname) >= 4 and surname.casefold() not in ambiguous_single_word_aliases:
                aliases.add(surname)
                aliases.add(f"{surname}’s")
                aliases.add(f"{surname}'s")

        if "of" in {token.casefold() for token in title_tokens[1:-1]}:
            leading_name = title_tokens[0]
            if leading_name and len(leading_name) >= 4 and leading_name.casefold() not in ambiguous_single_word_aliases:
                aliases.add(leading_name)
                aliases.add(f"{leading_name}’s")
                aliases.add(f"{leading_name}'s")

        aliases_by_href[path.name] = {alias for alias in aliases if alias}

    alias_counts: dict[str, int] = {}
    for aliases in aliases_by_href.values():
        for alias in aliases:
            alias_counts[alias.casefold()] = alias_counts.get(alias.casefold(), 0) + 1

    unique_aliases: dict[str, tuple[str, ...]] = {}
    for href, aliases in aliases_by_href.items():
        kept = [alias for alias in aliases if alias_counts.get(alias.casefold(), 0) == 1]
        kept.sort(key=lambda value: (-len(value), value.casefold()))
        if kept:
            unique_aliases[href] = tuple(kept)
    return unique_aliases


def autolink_entry_pages(page: str, context: PageContext) -> str:
    if context.filename in {"index.html", "about.html", "glossary.html"}:
        return page

    main_match = MAIN_RE.search(page)
    if not main_match:
        return page

    main_content = main_match.group(2)
    article_re = re.compile(r'(<article\b[^>]*class="[^"]*\bessay\b[^"]*"[^>]*>)(.*?)(</article>)', re.S)

    def repl(match: re.Match[str]) -> str:
        article_open, article_content, article_close = match.group(1), match.group(2), match.group(3)
        article_content = re.sub(
            r'<a\b[^>]*class="[^"]*\bphilosopher-link\b[^"]*"[^>]*>(.*?)</a>',
            lambda stale: stale.group(1),
            article_content,
            flags=re.S,
        )
        existing_links = set(re.findall(r'href="([^"]+)"', article_content))
        updated = article_content
        for href, aliases in entry_page_aliases().items():
            if href == context.filename or href in existing_links:
                continue
            updated, linked = autolink_entry_once(updated, href, aliases)
            if linked:
                existing_links.add(href)
        return f"{article_open}{updated}{article_close}"

    main_content = article_re.sub(repl, main_content)
    return "".join(
        (
            page[: main_match.start()],
            main_match.group(1),
            main_content,
            main_match.group(3),
            page[main_match.end() :],
        )
    )


def autolink_entry_once(content: str, href: str, variants: tuple[str, ...]) -> tuple[str, bool]:
    pattern = re.compile(
        r"\b(?:" + "|".join(re.escape(variant).replace(r"\ ", r"\s+") for variant in variants) + r")\b",
        re.I,
    )
    parts = re.split(r'(<a\b[^>]*>.*?</a>|<[^>]+>)', content, flags=re.S)

    for index, part in enumerate(parts):
        if not part or part.startswith("<"):
            continue
        match = pattern.search(part)
        if not match:
            continue
        matched_text = match.group(0)
        replacement = f'<a class="gloss-term philosopher-link" href="{href}">{matched_text}</a>'
        parts[index] = part[: match.start()] + replacement + part[match.end() :]
        return "".join(parts), True

    return content, False


def autolink_term_once(content: str, term_id: str, variants: tuple[str, ...], definition: str) -> tuple[str, bool]:
    pattern = re.compile(
        r"\b(?:" + "|".join(re.escape(variant).replace(r"\ ", r"\s+") for variant in variants) + r")\b",
        re.I,
    )
    definition_attr = html.escape(definition, quote=True)
    parts = re.split(r'(<a\b[^>]*>.*?</a>|<[^>]+>)', content, flags=re.S)

    for index, part in enumerate(parts):
        if not part or part.startswith("<"):
            continue
        match = pattern.search(part)
        if not match:
            continue
        matched_text = match.group(0)
        replacement = (
            f'<a class="gloss-term" data-def="{definition_attr}" '
            f'href="glossary.html#{term_id}">{matched_text}</a>'
        )
        parts[index] = part[: match.start()] + replacement + part[match.end() :]
        return "".join(parts), True

    return content, False


def build_all(site_dir: Path = SITE_DIR) -> list[Path]:
    changed: list[Path] = []
    for path in sorted(site_dir.glob("*.html")):
        source = path.read_text(encoding="utf-8")
        context = infer_page_context(source, path.name)
        built = build_page(source, context)
        if built != source:
            path.write_text(built, encoding="utf-8")
            changed.append(path)
    return changed


def main() -> int:
    changed = build_all()
    print(f"Updated {len(changed)} page(s).")
    for path in changed[:10]:
        print(f"- {path.name}")
    if len(changed) > 10:
        print(f"... and {len(changed) - 10} more")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
