from pathlib import Path
import sys
import tempfile
import textwrap
import unittest

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from tools.build_site import PageContext, build_page, render_header  # noqa: E402


class BuildSiteTests(unittest.TestCase):
    def test_render_header_uses_real_buttons_with_accessibility_attributes(self):
        header = render_header(
            PageContext(
                filename="descartes.html",
                title="René Descartes · Digital Minds",
                active_top_link=None,
                active_group="early-modern",
                active_page="early-modern.html",
            )
        )

        self.assertIn('<button type="button" class="nav-link nav-label"', header)
        self.assertIn('aria-expanded="false"', header)
        self.assertIn('aria-controls="submenu-early-modern"', header)
        self.assertIn('id="submenu-early-modern"', header)

    def test_build_page_replaces_legacy_chrome_and_injects_site_script(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>René Descartes · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header">
              <div class="site-header-inner">
                old header
              </div>
            </header>
            <main>
              <article class="essay"><p>Body stays here.</p></article>
            </main>
            <footer class="site-footer">
              <p>old footer</p>
            </footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="descartes.html",
                title="René Descartes · Digital Minds",
                active_top_link=None,
                active_group="early-modern",
                active_page="early-modern.html",
            ),
        )

        self.assertIn('<!-- Generated by tools/build_site.py: do not edit header/footer by hand. -->', built)
        self.assertIn('<article class="essay"><p>Body stays here.</p></article>', built)
        self.assertIn('<script src="site.js" defer></script>', built)
        self.assertNotIn('old header', built)
        self.assertNotIn('old footer', built)

    def test_build_page_is_idempotent(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>About &middot; Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header">
              <div class="site-header-inner">old header</div>
            </header>
            <main><p>About body.</p></main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        context = PageContext(
            filename="about.html",
            title="About &middot; Digital Minds",
            active_top_link="about.html",
            active_group=None,
            active_page=None,
        )
        first = build_page(source, context)
        second = build_page(first, context)

        self.assertEqual(first, second)

    def test_build_page_makes_glossary_terms_mobile_friendly(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>René Descartes · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p><a class="gloss-term" data-def="A definition" href="glossary.html#term">term</a></p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="descartes.html",
                title="René Descartes · Digital Minds",
                active_top_link=None,
                active_group="early-modern",
                active_page="early-modern.html",
            ),
        )

        self.assertIn('data-glossary-enhanced="true"', built)
        self.assertIn('class="gloss-term"', built)
        self.assertIn('data-def="A definition"', built)
        self.assertIn('href="glossary.html#term"', built)

    def test_build_page_normalizes_plain_glossary_hash_links_into_gloss_terms(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Consciousness Science · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <section class="era-page">
                <p>The field ranges from <a href="glossary.html#global-neuronal-workspace">global neuronal workspace</a> models onward.</p>
              </section>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="consciousness-science.html",
                title="Consciousness Science · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="consciousness-science.html",
            ),
        )

        self.assertIn('href="glossary.html#global-neuronal-workspace"', built)
        self.assertIn('class="gloss-term"', built)
        self.assertIn('data-glossary-enhanced="true"', built)
        self.assertRegex(built, r'data-def="[^"]+"')

    def test_build_page_removes_glossary_links_from_subtitles_but_keeps_main_content_links(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Stanislas Dehaene · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <header class="essay-header">
                <p class="standfirst">The <a href="glossary.html#global-neuronal-workspace">global neuronal workspace</a> as subtitle text.</p>
              </header>
              <article class="essay">
                <p>Main body discussion still uses intentionality in the primary content block.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="dehaene.html",
                title="Stanislas Dehaene · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="consciousness-science.html",
            ),
        )

        self.assertIn('<p class="standfirst">The global neuronal workspace as subtitle text.</p>', built)
        self.assertIn('href="glossary.html#intentionality"', built)

    def test_build_page_autolinks_first_occurrence_of_selected_glossary_term(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Bernard Baars · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Baars treats intentionality as part of the mind's structured aboutness.</p>
                <p>Later sections can return to intentionality without another automatic link.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="baars.html",
                title="Bernard Baars · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="consciousness-science.html",
            ),
        )

        self.assertIn('href="glossary.html#intentionality"', built)
        self.assertEqual(built.count('href="glossary.html#intentionality"'), 1)
        self.assertIn('data-glossary-enhanced="true"', built)

    def test_build_page_does_not_duplicate_existing_glossary_link_for_same_term(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Bernard Baars · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p><a class="gloss-term" data-def="Aboutness." href="glossary.html#intentionality">intentionality</a> already has a glossary link.</p>
                <p>A later mention of intentionality should stay plain text.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="baars.html",
                title="Bernard Baars · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="consciousness-science.html",
            ),
        )

        self.assertEqual(built.count('href="glossary.html#intentionality"'), 1)

    def test_build_page_autolinks_new_second_wave_term(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Andy Clark · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Clark's work helped reshape debates about the extended mind in philosophy of mind.</p>
                <p>Later mentions of the extended mind can remain plain text.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="clark.html",
                title="Andy Clark · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="machine-minds.html",
            ),
        )

        self.assertIn('href="glossary.html#extended-mind"', built)
        self.assertEqual(built.count('href="glossary.html#extended-mind"'), 1)

    def test_build_page_autolinks_theory_of_mind_phrase(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Michael Tomasello · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Developmental psychologists often discuss theory of mind when explaining how children understand other agents.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="tomasello.html",
                title="Michael Tomasello · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="moral-status.html",
            ),
        )

        self.assertIn('href="glossary.html#theory-of-mind"', built)
        self.assertEqual(built.count('href="glossary.html#theory-of-mind"'), 1)

    def test_build_page_autolinks_active_inference(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Karl Friston · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>His framework links perception, action, and active inference within one predictive model.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="friston.html",
                title="Karl Friston · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="consciousness-science.html",
            ),
        )

        self.assertIn('href="glossary.html#active-inference"', built)
        self.assertEqual(built.count('href="glossary.html#active-inference"'), 1)

    def test_build_page_autolinks_joint_attention(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Jerome Bruner · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Language learning depends heavily on joint attention between child and caregiver.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="bruner.html",
                title="Jerome Bruner · Digital Minds",
                active_top_link=None,
                active_group="modern",
                active_page="analytic.html",
            ),
        )

        self.assertIn('href="glossary.html#joint-attention"', built)
        self.assertEqual(built.count('href="glossary.html#joint-attention"'), 1)

    def test_build_page_autolinks_supervenience(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>David Lewis · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Many physicalists explain mental difference in terms of supervenience on physical difference.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="lewis.html",
                title="David Lewis · Digital Minds",
                active_top_link=None,
                active_group="modern",
                active_page="analytic.html",
            ),
        )

        self.assertIn('href="glossary.html#supervenience"', built)
        self.assertEqual(built.count('href="glossary.html#supervenience"'), 1)

    def test_build_page_autolinks_philosopher_names_to_existing_entry_pages(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Kristin Andrews · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Andrews presents Aquinas as a major boundary marker in the history of animal minds.</p>
                <p>A later mention of Aquinas can remain plain text.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="andrews.html",
                title="Kristin Andrews · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="moral-status.html",
            ),
        )

        self.assertIn('href="aquinas.html"', built)
        self.assertEqual(built.count('href="aquinas.html"'), 1)
        self.assertIn('class="gloss-term philosopher-link"', built)

    def test_build_page_does_not_self_link_current_philosopher_name(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Thomas Aquinas · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Aquinas develops a hylomorphic account of soul, while Augustine remains an important interlocutor.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="aquinas.html",
                title="Thomas Aquinas · Digital Minds",
                active_top_link=None,
                active_group="ancient-medieval",
                active_page="scholasticism.html",
            ),
        )

        self.assertNotIn('href="aquinas.html"', built)
        self.assertIn('href="augustine.html"', built)

    def test_build_page_does_not_link_generic_honorific_tail_words_as_philosopher_names(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Kristin Andrews · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Her critique also reaches the older theological hierarchy of the Great Chain of Being.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="andrews.html",
                title="Kristin Andrews · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="moral-status.html",
            ),
        )

        self.assertNotIn('href="albert.html"', built)
        self.assertIn('Great Chain of Being', built)

    def test_build_page_autolinks_safe_possessive_surname_variant(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Thomas Aquinas · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Augustine’s inwardness differs from Aquinas’s hylomorphic account of soul and intellect.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="augustine.html",
                title="Augustine of Hippo · Digital Minds",
                active_top_link=None,
                active_group="ancient-medieval",
                active_page="late-antiquity.html",
            ),
        )

        self.assertIn('href="aquinas.html"', built)
        self.assertIn('>Aquinas’s</a>', built)

    def test_build_page_does_not_link_common_word_like_surname_in_plain_usage(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>William James · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>The publication list is long, and one notebook uses a brown cover for field observations.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="james.html",
                title="William James · Digital Minds",
                active_top_link=None,
                active_group="modern",
                active_page="nineteenth-century.html",
            ),
        )

        self.assertNotIn('href="list.html"', built)
        self.assertNotIn('href="long.html"', built)
        self.assertNotIn('href="brown.html"', built)
        self.assertIn('publication list is long', built)

    def test_build_page_does_not_link_short_name_aliases_inside_roman_numerals(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Augustine of Hippo · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Read together, <em>Confessions</em> X–XI, <em>De libero arbitrio</em>, and <em>De Trinitate</em>.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="augustine.html",
                title="Augustine of Hippo · Digital Minds",
                active_top_link=None,
                active_group="ancient-medieval",
                active_page="late-antiquity.html",
            ),
        )

        self.assertNotIn('href="zhu-xi.html"', built)
        self.assertIn('X–XI', built)

    def test_build_page_recomputes_existing_philosopher_links_when_alias_rules_change(self):
        source = textwrap.dedent(
            """\
            <!DOCTYPE html>
            <html lang="en">
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1">
              <title>Kristin Andrews · Digital Minds</title>
              <link rel="stylesheet" href="style.css">
            </head>
            <body>
            <header class="site-header"><div class="site-header-inner">old header</div></header>
            <main>
              <article class="essay">
                <p>Her critique also reaches the older theological hierarchy of the <a class="gloss-term philosopher-link" href="albert.html">Great</a> Chain of Being.</p>
              </article>
            </main>
            <footer class="site-footer"><p>old footer</p></footer>
            </body>
            </html>
            """
        )

        built = build_page(
            source,
            PageContext(
                filename="andrews.html",
                title="Kristin Andrews · Digital Minds",
                active_top_link=None,
                active_group="contemporary",
                active_page="moral-status.html",
            ),
        )

        self.assertNotIn('href="albert.html"', built)
        self.assertIn('Great Chain of Being', built)


if __name__ == "__main__":
    unittest.main()
